### ISSUE TITLE
No reaction on file in target folder

### ISSUE THREAD

**Issue by Ursus63** [bpopp/Octoprint-Cura-Superslicer-Uploader#7]
Hello. I used your app befor. And all was OK. But after Windows reinstall there is no reaction on file in target folder. Check button says Successfully connected. But nothing else. 
Is there any network, windows or octoprint settings i need to configure? I tried to disable my firewall, but it didn't help.

**Comment by bpopp** [comment]
I've actually had this happen to me a couple times, too.  I'll debug and see if I can figure out what's going on. Thanks for the feedback.

**Comment by bpopp** [comment]
I added a new version (1.4) that should log important events to C:\ProgramData\OctoUploader. Please install and if you see this issue again, upload a copy of your log. If you don't want to publish your log (API keys are not included), you can email it to me.

**Comment by Ursus63** [comment]
Hello.
No reaction on file in target folder in log too. Uninitializing filesystem watcher - this when i open settings.

```
2019-12-27 14:01:00.322 +04:00 [INF] Logger started
2019-12-27 14:01:00.477 +04:00 [INF] Watching C:\Users\ursus\Desktop\Gcode for server address http://zav.local/
2019-12-27 14:01:00.478 +04:00 [INF] Initializing filesystem watcher @ C:\Users\ursus\Desktop\Gcode
2019-12-27 14:01:03.000 +04:00 [INF] Uninitializing filesystem watcher.
2019-12-27 14:01:17.408 +04:00 [INF] Watching C:\Users\ursus\Desktop\Gcode for server address http://zav.local/
2019-12-27 14:01:17.408 +04:00 [INF] Initializing filesystem watcher @ C:\Users\ursus\Desktop\Gcode
2019-12-27 14:02:45.694 +04:00 [INF] Opening Octoprint using address http://zav.local/
2019-12-27 14:02:50.932 +04:00 [INF] Uninitializing filesystem watcher.
2019-12-27 14:02:57.650 +04:00 [INF] Watching C:\Users\ursus\Desktop\Gcode for server address http://zav.local/
2019-12-27 14:02:57.651 +04:00 [INF] Initializing filesystem watcher @ C:\Users\ursus\Desktop\Gcode
```

**Comment by bpopp** [comment]
Everything there looks normal. That's really odd. You're sure you're saving the file into that folder? Open the start menu, press spacebar, paste or type C:\Users\ursus\Desktop\Gcode and then hit enter. Make sure that a gcode file appears there when you save it from your 3d printing application. If you're using OneDrive (and possibly other cloud apps), it can do weird things with your desktop and documents folder and hijack the location so that your "desktop" is actually stored in the onedrive folder. Try using another folder as your watch folder (maybe at the root of your C drive).

**Comment by bpopp** [comment]
Going to close this out because the latest release seems to have fixed the occasional issue I was seeing with files not uploading. It sounds like this might be a different issue than what you were seeing, but hopefully you figured out what was going on. If not, comment or add another issue and I'll take a look.

**Comment by Ursus63** [comment]
Unfortunately i have the same issue with latest realese.
I tried to use folders in different locations and with different names including root of С drive.
It's a pity that i can't use your app.

**Comment by Ursus63** [comment]
Hello.
Just want to leave a comment for someone who have the same issue.
I reinstall my Windows 10 and decided to try install OctoUploader again after a year with out it. And I have the same problem. But when I changed target folder path to root of drive D, it starts to work fine. Don't know why, but in any other folders on disk С it does't want to work.

**Comment by bpopp** [comment]
Interesting. Thanks for the comment. All I can think is that it's permissions related. Anything weird with the user that is running the OctoUploader program? Any reason they wouldn't have permissions to read the C drive?

**Comment by Ursus63** [comment]
No such reasons. Only one user with administration rights at this PC. I probably can understand some special permeations for root of disk C, but for desktop? Don't know eventually.
